#!/usr/bin/env node
// catalog-compile.js — compile the vendored star and constellation data
// into src/catalog/data/ modules.
//
// Sources (vendored under tools/data/catalog/, from the Yale Bright Star
// Catalogue, 5th ed., and a hand-built constellation line-figure set):
//   bsc_{short,mid,long}.json.gz  stars, equinox and epoch J2000.0
//   constellations.json           88 figures as star lists + line pairs
//
// The shipped star module is the "short" tier (naked-eye bright stars,
// V <= 5); the fuller tiers stay vendored for on-demand builds. The
// constellation figures are emitted whole. The compiler self-checks the
// record shape and that every line index points at an existing star.
//
// Usage: node tools/catalog-compile.js [--tier short|mid|long]

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(__dirname, 'data', 'catalog');
const OUT_DIR = path.join(ROOT, 'src', 'catalog', 'data');

// The vendored JSON carries trailing commas (a quirk of the original
// hand-maintained files), so it is not strict JSON: strip them first.
const loadLoose = (file, gz) => {
  const raw = gz
    ? zlib.gunzipSync(fs.readFileSync(file)).toString('utf8')
    : fs.readFileSync(file, 'utf8');
  return JSON.parse(raw.replace(/,(\s*[\]}])/g, '$1'));
};

// IAU constellation abbreviation from a Bayer/Flamsteed id, e.g.
// "58Alp Ori" -> "Ori", "Alp1Cen" -> "Cen", "51 And" -> "And".
const abbrevOf = (bfID) => String(bfID).trim().slice(-3);

const compileStars = (tier) => {
  const cat = loadLoose(path.join(SRC_DIR, `bsc_${tier}.json.gz`), true).BSC;
  const stars = cat.map((s) => {
    const rec = {
      hr: Number(s.HR),
      bf: String(s.bfID || '').trim(),
      con: abbrevOf(s.bfID),
      ra: Number(s.RAh),   // hours, J2000
      dec: Number(s.DEd),  // degrees, J2000
      mag: Number(s.Vmag),
      pmRA: Number(s.pmRA) || 0, // arcsec/yr on the sky (includes cos dec)
      pmDE: Number(s.pmDE) || 0  // arcsec/yr
    };
    const name = s.Name && String(s.Name).trim();
    if (name) rec.name = name;
    if (!Number.isFinite(rec.ra) || !Number.isFinite(rec.dec) || !Number.isFinite(rec.mag)) {
      throw new Error('bad star record: ' + JSON.stringify(s));
    }
    return rec;
  });
  stars.sort((a, b) => a.mag - b.mag); // brightest first
  const rows = stars.map((s) => '  ' + JSON.stringify(s)).join(',\n');
  const out =
    `// bright-star catalogue (${tier} tier) — GENERATED by tools/catalog-compile.js; do not edit.\n` +
    `// Source: Yale Bright Star Catalogue, 5th ed. (Hoffleit & Warren 1991),\n` +
    `// equinox and epoch J2000.0. ${stars.length} stars, V <= ${stars[stars.length - 1].mag}.\n` +
    `// Fields: hr, bf (Bayer/Flamsteed), con (IAU abbrev), ra (hours),\n` +
    `//   dec (deg), mag (V), pmRA/pmDE (arcsec/yr), name? (proper name).\n` +
    `export const STARS = [\n${rows}\n];\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'bright-stars.js'), out);
  return stars.length;
};

const compileConstellations = () => {
  const list = loadLoose(path.join(SRC_DIR, 'constellations.json'), false).Constellations;
  const figs = list.map((c) => {
    const stars = c.stars.map((s) => ({
      bf: String(s.bfID || '').trim(),
      ra: Number(s.RAh), dec: Number(s.DEd)
    }));
    const lines = (c.lines || []).map((p) => [Number(p[0]), Number(p[1])]);
    // self-check: every line index must reference an existing star
    for (const [a, b] of lines) {
      if (!stars[a] || !stars[b]) {
        throw new Error(`${c.Name}: line [${a},${b}] out of range (${stars.length} stars)`);
      }
    }
    return { name: c.Name, ra: Number(c.RAh), dec: Number(c.DEd), stars, lines };
  });
  const rows = figs.map((f) =>
    `  { name: ${JSON.stringify(f.name)}, ra: ${f.ra}, dec: ${f.dec},\n` +
    `    stars: ${JSON.stringify(f.stars)},\n` +
    `    lines: ${JSON.stringify(f.lines)} }`).join(',\n');
  const out =
    `// constellation figures — GENERATED by tools/catalog-compile.js; do not edit.\n` +
    `// ${figs.length} constellations. Each: center (ra hours / dec deg), a\n` +
    `// star list (Bayer/Flamsteed id + J2000 ra/dec), and 'lines' as index\n` +
    `// pairs into that list describing the drawn figure.\n` +
    `export const CONSTELLATIONS = [\n${rows}\n];\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'constellations.js'), out);
  return figs.length;
};

const main = () => {
  const tierArg = process.argv.indexOf('--tier');
  const tier = tierArg >= 0 ? process.argv[tierArg + 1] : 'short';
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const nStars = compileStars(tier);
  const nCons = compileConstellations();
  console.log(`catalog: ${nStars} stars (${tier} tier), ${nCons} constellations`);
};

try {
  main();
} catch (e) {
  console.error(e.message);
  process.exit(1);
}
