#!/usr/bin/env node
// vsop-compile.js — compile ephemeris coefficient tables into per-body
// Float64Array modules under src/bodies/data/.
//
// Sources:
//  - VSOP87A (Bretagnon & Francou 1988): read from the v3 source file
//    src/orb-vsop87a.js, so no coefficient is ever re-typed by hand.
//    Each row is [component(0=x,1=y,2=z), power_of_t, A, B, C] meaning
//    the term  t^power * A * cos(B + C*t)  with t in thousands of Julian
//    years from J2000 and A in au.
//  - The Meeus ch. 47 lunar tables: extracted from src/orb-luna.js.
//
// For every planet two variants are produced:
//  - vsop87a-<planet>.js       truncated series (default import): terms
//    are dropped smallest-first while the accumulated angular error seen
//    from Earth stays below TARGET_ARCSEC.
//  - vsop87a-<planet>.full.js  the complete series.
//
// Usage: node tools/vsop-compile.js

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'src', 'bodies', 'data');

const TARGET_ARCSEC = 0.1;
const ARCSEC_RAD = Math.PI / 180 / 3600;

// Minimum geocentric distance (au): converts an in-space displacement
// into the worst-case angle an Earth observer could see.
const MIN_GEO_DIST = {
  mercury: 0.52, venus: 0.26, earth: 1.0, mars: 0.37,
  jupiter: 3.9, saturn: 8.0, uranus: 17.3, neptune: 28.8
};

// t-span used to weight powered terms: |t| <= 0.5 covers 1500-2500 AD.
const T_MAX = 0.5;

const loadV3Coefficients = async () => {
  const mod = await import('file://' + path.join(ROOT, 'src', 'orb-vsop87a.js'));
  return {
    mercury: mod.MERCURY_COEF, venus: mod.VENUS_COEF, earth: mod.EARTH_COEF,
    mars: mod.MARS_COEF, jupiter: mod.JUPITER_COEF, saturn: mod.SATURN_COEF,
    uranus: mod.URANUS_COEF, neptune: mod.NEPTUNE_COEF
  };
};

// rows -> { x: [terms by power], y: ..., z: ... }, terms sorted by
// descending amplitude inside each power block.
const organize = (rows) => {
  const comp = [[], [], []];
  for (const row of rows) {
    const [n, p, a, b, c] = row.map(Number);
    (comp[n][p] = comp[n][p] || []).push([a, b, c]);
  }
  for (const axis of comp) {
    for (const block of axis) {
      if (block) block.sort((u, v) => Math.abs(v[0]) - Math.abs(u[0]));
    }
  }
  return comp;
};

// Truncate: drop the smallest effective amplitudes (|A| * T_MAX^power)
// while the sum of everything dropped stays below the tolerance in au.
const truncate = (comp, tolAu) => {
  const all = [];
  comp.forEach((axis, n) => axis.forEach((block, p) => {
    if (block) block.forEach((term, i) => {
      all.push({ n, p, i, eff: Math.abs(term[0]) * Math.pow(T_MAX, p) });
    });
  }));
  all.sort((a, b) => a.eff - b.eff);
  const dropped = new Set();
  let budget = tolAu;
  for (const item of all) {
    if (item.eff > budget) break;
    budget -= item.eff;
    dropped.add(item.n + ':' + item.p + ':' + item.i);
  }
  return comp.map((axis, n) => axis.map((block, p) =>
    block ? block.filter((_, i) => !dropped.has(n + ':' + p + ':' + i)) : block
  ));
};

const countTerms = (comp) =>
  comp.reduce((s, axis) => s + axis.reduce((t, b) => t + (b ? b.length : 0), 0), 0);

const renderModule = (name, comp, note) => {
  const axes = ['X', 'Y', 'Z'];
  let out = `// vsop87a data for ${name} — GENERATED by tools/vsop-compile.js; do not edit.\n` +
    `// Source: VSOP87A, Bretagnon & Francou (1988), via the v3 coefficient file.\n` +
    `// ${note}\n` +
    `// Layout per axis: array indexed by power of t, each entry a flat\n` +
    `// Float64Array of [A, B, C] triples for  t^power * A*cos(B + C*t),\n` +
    `// t in thousands of Julian years (TT) from J2000, A in au.\n`;
  comp.forEach((axis, i) => {
    out += `export const ${axes[i]} = [\n`;
    axis.forEach((block) => {
      const flat = block ? block.flat() : [];
      out += `  new Float64Array([${flat.map(String).join(', ')}]),\n`;
    });
    out += '];\n';
  });
  return out;
};

const extractLunaTables = () => {
  const text = fs.readFileSync(path.join(ROOT, 'src', 'orb-luna.js'), 'utf8');
  const grab = (key) => {
    const m = text.match(new RegExp(key + ':\\s*\\[([\\s\\S]*?)\\n  \\]'));
    if (!m) throw new Error('luna table ' + key + ' not found');
    return m[1].match(/\[[^\]]+\]/g).map((row) => JSON.parse(row));
  };
  return { LR: grab('LR'), B: grab('B') };
};

const main = async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const planets = await loadV3Coefficients();
  const report = [];
  for (const [name, rows] of Object.entries(planets)) {
    const full = organize(rows);
    const tolAu = TARGET_ARCSEC * ARCSEC_RAD * MIN_GEO_DIST[name];
    const short = truncate(full, tolAu);
    fs.writeFileSync(path.join(OUT_DIR, `vsop87a-${name}.full.js`),
      renderModule(name, full, `Full series: ${countTerms(full)} terms.`));
    fs.writeFileSync(path.join(OUT_DIR, `vsop87a-${name}.js`),
      renderModule(name, short,
        `Truncated: ${countTerms(short)}/${countTerms(full)} terms; accumulated ` +
        `truncation error < ${TARGET_ARCSEC}" seen from Earth (1500-2500 AD).`));
    report.push(`${name}: ${countTerms(short)}/${countTerms(full)} terms`);
  }

  const luna = extractLunaTables();
  let lunaOut = `// Meeus ch. 47 lunar periodic terms — GENERATED by tools/vsop-compile.js\n` +
    `// from the v3 source (orb-luna.js); do not edit. Reference: Meeus,\n` +
    `// Astronomical Algorithms 2nd ed., tables 47.a / 47.b.\n` +
    `// LR rows: [D, M, M', F, sin-coeff for longitude (1e-6 deg),\n` +
    `//           cos-coeff for distance (1e-3 km)]\n` +
    `// B rows:  [D, M, M', F, sin-coeff for latitude (1e-6 deg)]\n`;
  lunaOut += `export const LR = [\n${luna.LR.map((r) => `  [${r.join(', ')}],`).join('\n')}\n];\n`;
  lunaOut += `export const B = [\n${luna.B.map((r) => `  [${r.join(', ')}],`).join('\n')}\n];\n`;
  fs.writeFileSync(path.join(OUT_DIR, 'moon-meeus.js'), lunaOut);
  report.push(`moon: LR ${luna.LR.length} rows, B ${luna.B.length} rows`);

  console.log(report.join('\n'));
};

main().catch((e) => { console.error(e); process.exit(1); });
